version: "3"

services:
  workspace:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        ARG_BUILD_FROM: $BUILD_FROM
        ARG_USERNAME: $USERNAME
        ARG_USER_UID: $USER_UID
        ARG_USER_GID: $USER_GID
        ARG_USER_FULLNAME: $USER_FULLNAME
        ARG_USER_EMAIL: $USER_EMAIL
        ARG_GITHUB_USERNAME: $GITHUB_USERNAME
        ARG_SYSTEM_HOSTNAME: $CONTAINER_HOSTNAME
        ARG_WORKSPACE_LOCATION: $CONTAINER_WORKSPACE_LOCATION
        ARG_WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
    image: $IMAGE_NAME
    hostname: $CONTAINER_HOSTNAME
    command:
      - bash
      - /home/$USERNAME/scripts/devenv-entrypoint.sh
    environment:
      USER_FULLNAME: $USER_FULLNAME
      USER_EMAIL: $USER_EMAIL
      GITHUB_USERNAME: $GITHUB_USERNAME
      WORKSPACE_LOCATION: $CONTAINER_WORKSPACE_LOCATION
      WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
      SYSTEM_HOSTNAME: $CONTAINER_HOSTNAME
      HOST_JUPYTER_PORT: $HOST_JUPYTER_PORT
      JUPYTER_TOKEN: $JUPYTER_TOKEN
      JUPYTER_PORT: $JUPYTER_PORT
    ulimits:
      stack: 67108864
      memlock: -1
    ipc: host
    ports:
      - "$HOST_SSH_PORT:22"
      - "$HOST_JUPYTER_PORT:$JUPYTER_PORT"
    volumes:
      - "$HOME/.ssh:/home/$USERNAME/.ssh"
      - "$HOME/.config/gh:/home/$USERNAME/.config/gh"
      - "$HOME/.password-store:/home/$USERNAME/.password-store"
      - "$HOME/.passage:/home/$USERNAME/.passage"
      - "$HOME/.cache/huggingface:/home/$USERNAME/.cache/huggingface"
      - "$HOME/.huggingface:/home/$USERNAME/.huggingface"
      - "$WORKSPACE_ROOT:$CONTAINER_WORKSPACE_ROOT"
      - "$PWD/.docker/scripts:/home/$USERNAME/scripts"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${CUDA_DEVICE_ID}"]
              capabilities: [gpu]
networks:
  default:
    name: $DOCKER_NETWORK_NAME
    external: true
