version: "3"

services:
  workspace:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        ARG_BUILD_FROM: $BUILD_FROM
        ARG_USERNAME: $USERNAME
    image: $IMAGE_NAME
    hostname: $CONTAINER_HOSTNAME
    command:
      - bash
      # - /home/$USERNAME/scripts/devenv-entrypoint.sh
      - /home/$USERNAME/scripts/webui.sh
    environment:
      HOST_JUPYTER_PORT: $HOST_JUPYTER_PORT
      JUPYTER_TOKEN: $JUPYTER_TOKEN
      JUPYTER_PORT: $JUPYTER_PORT
      WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
    env_file:
      - .docker/scripts/webui.env
    ulimits:
      stack: 67108864
      memlock: -1
    ipc: host
    ports:
      - "$HOST_SSH_PORT:22"
      - "$HOST_JUPYTER_PORT:$JUPYTER_PORT"
      - "$HOST_GRADIO_PORT:$GRADIO_PORT"
    volumes:
      - "$HOME/.ssh:/home/$USERNAME/.ssh"
      - "$HOME/.config/gh:/home/$USERNAME/.config/gh"
      - "$HOME/.password-store:/home/$USERNAME/.password-store"
      - "$HOME/.passage:/home/$USERNAME/.passage"
      - "$HOME/.cache/huggingface:/home/$USERNAME/.cache/huggingface"
      - "$HOME/.huggingface:/home/$USERNAME/.huggingface"
      - "$WORKSPACE_ROOT:$CONTAINER_WORKSPACE_ROOT"
      - "$PWD/.docker/scripts:/home/$USERNAME/scripts"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${CUDA_DEVICE_ID}"]
              capabilities: [gpu]
networks:
  default:
    name: $DOCKER_NETWORK_NAME
    external: true
