forticlient:
    name: null
    descriptions: null
    gateway: ENC[AES256_GCM,data:nLQr/fiC52BzCrQ=,iv:jw4vBxeYNaqDpRZb66YBKAOxhIE6rZYlgTAIrmWYbJM=,tag:a/OPP0WlniLLupzSM0jAvQ==,type:str]
    port: ENC[AES256_GCM,data:R0uW1us=,iv:zdQ3AJtrrkkx/adJWbtWHqDtFQEimy7em6hxplREnmI=,tag:x8eLN6grUK4aah2W0oPGWA==,type:int]
users:
    chuai1: ENC[AES256_GCM,data:4+N69wEPckVSsLA=,iv:8pYVrDSd7hdHNmRwNft/A+9PrCUkY32PRfi0jqQY4wg=,tag:ceByRpMQfP8JSxIOfZJnAA==,type:str]
    chuai2: ENC[AES256_GCM,data:I8GaMC2+nksz8Tk=,iv:EXrlAB5bOSFUyF/021KjgE9LVJb9U60KEK32OESIPJI=,tag:thFxMrg135qmtkI4AVGl2Q==,type:str]
    chuai3: ENC[AES256_GCM,data:itrIlrB31ejphZY2,iv:ZWW+Y4D5S1581czXA1ZHEAO+7sNcA1ZVPlUowk43Etg=,tag:XYuvniNzhrxq6qBYEfjQSw==,type:str]
    chuai4: ENC[AES256_GCM,data:BDsWCOIa2xN2Xuo=,iv:2Mp2C02VU5TQ2UPtGuJihRT0aGnoGb1fFiVtJQV5mCQ=,tag:maGLEYTZwsQxgZX/jGxYJg==,type:str]
    chuai5: ENC[AES256_GCM,data:KLAQZSftnN3iGdI=,iv:rLdvX27ffzO6i4Zt+2EYPIzgQ3AfC/pyTFymwCq2iic=,tag:4vF7r54p2QrfDfFlbPq63A==,type:str]
    chuai6: ENC[AES256_GCM,data:XPPeGv/0diMhYMwo,iv:Wf4A81l5M8b0bZRidY9r5aQW2HHDz01Sza/lXobZacM=,tag:9iQj1ak4gnTV1x2UGg7C2Q==,type:str]
    chuai7: ENC[AES256_GCM,data:tQhTsHwM6hLnjFs=,iv:Nu3w68u2ybBnmpLreJNh86xrf0Zp433xtMjoHQsbvi8=,tag:98Ea0LCgRgYb5aWdrhExyQ==,type:str]
    chuai8: ENC[AES256_GCM,data:2uogLthCj5FAadI=,iv:aVWNHH9GTIl4rT+1tiNlCogPwpzKquplQ8eumwBPQJY=,tag:lofle90raDlry+uJocyUBQ==,type:str]
servers:
    30.0.0.112: ENC[AES256_GCM,data:dOAr3sAotn3Vs6wLimc=,iv:/utOUggyG1hTYGjU2Ne/zOncc2DELXQBKH+8n1n/Sd0=,tag:dtQ2IsnYawi/0LBsgH4ygQ==,type:str]
    30.0.0.37: ENC[AES256_GCM,data:TSCnojHTcjArmacI//Y=,iv:Ccbuxm3xGZEYzKm0NZltntjASCSP8SKBbCk7ovmyTBU=,tag:/DVxt/JDlQcr3SUs90CP9A==,type:str]
    30.0.0.55: ENC[AES256_GCM,data:k2ov7byvkSDG74ut1Es=,iv:r55YXUeqnJIHy5E59Y1tJpNyxO4jvcoYRC8QoEkyJYU=,tag:LTEG09NnAvvN3R6+2g7N/A==,type:str]
    30.0.0.17: ENC[AES256_GCM,data:0jJtc+bBurqMy5S3l/k=,iv:z2EWXzQ24pCL1FwA0CNOunben3Eg95l3/M8PH4jhVIU=,tag:823+DGu/dUqnsZZNRbmSqw==,type:str]
    30.0.0.194: ENC[AES256_GCM,data:otJ2tKbvYURMqi1n1G0=,iv:QNR4jcC2DgFR0XheJUOAn7OLhp497uKPyTjQ/OMWKRU=,tag:mc2SDqTQ914KNYVEHaHSPw==,type:str]
    30.0.0.137: ENC[AES256_GCM,data:tTqfzLESdBNM4L5w2rY=,iv:FPcMO38wIUfxAfmcFxMcVt7vWGV7zgsKjW0jhqu+k4E=,tag:FpvT5r4X2sE2UQVnxtnHhg==,type:str]
    30.0.0.54: ENC[AES256_GCM,data:ciHb61js0ROtfZSjYKw=,iv:yFu07TMOQzyRheKBqKPFFpU0118lC5PrCXcRchkhXGw=,tag:vGo1HCBj2XUNEw3kslkwUw==,type:str]
    30.0.0.107: ENC[AES256_GCM,data:TrMiNdPFfdXmjiSts6w=,iv:LjbFvjnRHd03UCJGeNRA4O3qG/0UYQ7xCSfCMAi9Cks=,tag:xupj7/sAdLKLNX79taVmcA==,type:str]
    30.0.0.22: ENC[AES256_GCM,data:nLxFSwx+rYRMbRnsM/M=,iv:DNkYfNvbjqJq43w6X+Vvkf6F5JgVXNk972LQqa4d3YM=,tag:1nDmI4V9uhLUaflYvZzcNA==,type:str]
    30.0.0.67: ENC[AES256_GCM,data:ski+woWUqekMdwz97No=,iv:BLIOWV3ba/BrWLBQfUT5LdEjfzqA88IHINeKzQhz3yY=,tag:Uy0eHTzvtyHmj9gWzpi6yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16cmlxsvzsleydkafhksyk3s36d0yf2rld7xpl8u2xz0xycadwfpq8c4cjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGek1XdWlxZXByTStrSmJS
            dnh6MDBSNWsyalFGSEFkenZ6MFVoUGFmWW5VClRNeEtQMEgwRkd6NTcwam9MVXQw
            QWk3bW5LcUU2aEZzWmQ0c0J4Vk1xcXcKLS0tIHlBQVRLTG5yN0RxUjZSTDM2NDVF
            Vk5XeEc3M3JUK0NLN1FNYStjOWtHSzAKtln9Exv5q31LSs4dtPmoKdqbhohibRaK
            9vVE8Bf/RAumt/q+OXPO3BEDDiiPJ97Vp91kiDDpV1u1tH1YIgzFjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T07:04:14Z"
    mac: ENC[AES256_GCM,data:StXgr7h0imI2l5n7gt8WCUbYt78fLvoEiCRmA4uTpVZL6TgtDrYSGazBgWs9zVmd5owbpsN7l9sin7WPHS7h2j3Kz68FDUSTwMbVdI6+B2kP4VxTUrxxsoz/JhurjnbzTWT9DYg34+23fmGOD4XSWmEzXYTfXFvWl26IOfybvUE=,iv:YHIboN49mmshke4smKy4tc+HRa7v/aYNhhNKMeRko4w=,tag:hpP5s3Zb0xPuYY3ZFbY7Gw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
